### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by silchin-i** [Cristalix-Scripts/scripts#2]
Переместил _**CristalixHelper.ts**_ в _**/.cristalix/updates/Minigames/scripts**_, запустил кристу, скрипт не пашет. Запустил в режиме отладки, пишет вот что:

```
[main/ERROR]: Error loading script C:\Users\Ivan Silchin\.cristalix\updates\Minigames\scripts\CristalixHelper.ts
javax.script.ScriptException: SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found 

^ in <eval>
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:429) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:365) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:361) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:123) ~[nashorn.jar:?]
	at aiY.a( :96) ~[core-mod-1.12.2.jar:?]
	at aff.a( :177) [core-mod-1.12.2.jar:?]
	at aff.a( :147) [core-mod-1.12.2.jar:?]
	at fu.handler$zch000$onClientStarted( :4042) [minecraft.jar:?]
	at fu.ad( :550) [minecraft.jar:?]
	at fu.a( :353) [minecraft.jar:?]
	at net.minecraft.client.main.Main.main( :103) [minecraft.jar:?]
	at ru.cristalix.launcher.OOO000O0o MOJa OBoR0NA ZHARENII PoNCHIK VELIKOGO SALA.OOo0000oo MoJa ObORoNA pEPELNII KOLSHIK SHIROKoGo VOZa(Unknown Source) [CristalixLauncher-3.0.145.exe:?]
	at ru.cristalix.launcher.oooo0Oo0o_MoJA_OB0R0Na_PEpELNII_LaNLISH_SHIR0K0Go_BURA.OOo0000oo MoJa ObORoNA pEPELNII KOLSHIK SHIROKoGo VOZa(Unknown Source) [CristalixLauncher-3.0.145.exe:?]
	at ru.cristalix.launcher.oooo0Oo0o_MoJA_OB0R0Na_PEpELNII_LaNLISH_SHIR0K0Go_BURA.OOo0000oo MoJa ObORoNA pEPELNII KOLSHIK SHIROKoGo VOZa(Unknown Source) [CristalixLauncher-3.0.145.exe:?]
	at ru.cristalix.launcher.oooo0Oo0o_MoJA_OB0R0Na_PEpELNII_LaNLISH_SHIR0K0Go_BURA.main(Unknown Source) [CristalixLauncher-3.0.145.exe:?]
Caused by: jdk.nashorn.internal.runtime.ECMAException: SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found 

^
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:54) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:157) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:142) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:81) ~[nashorn.jar:?]
	at jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:119) ~[nashorn.jar:?]
	at ajx.load( :25) ~[core-mod-1.12.2.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:595) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:479) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:408) ~[nashorn.jar:?]
	... 14 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <json>:1:0 Expected json literal but found 

^
	at jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:529) ~[nashorn.jar:?]
	at jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:533) ~[nashorn.jar:?]
	at jdk.nashorn.internal.parser.JSONParser.expectedError(JSONParser.java:541) ~[nashorn.jar:?]
	at jdk.nashorn.internal.parser.JSONParser.parseLiteral(JSONParser.java:182) ~[nashorn.jar:?]
	at jdk.nashorn.internal.parser.JSONParser.parse(JSONParser.java:148) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:79) ~[nashorn.jar:?]
	at jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:119) ~[nashorn.jar:?]
	at ajx.load( :25) ~[core-mod-1.12.2.jar:?]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:595) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:479) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:408) ~[nashorn.jar:?]
	... 14 more
```

P.S.: Пользуясь случаем, спрошу. Есть где-то документация по мод апи действующему, или это не распространяется?

**Comment by silchin-i** [comment]
UPD:
вопрос в постскриптуме снят - https://github.com/DelfikPro/cristalix-client-api
решение возможных проблем - https:/go.microsoft.com/fwlink/?LinkID=135170
файл в папку закидывал неправильно, ошибки ушли
